У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [1]:
!ls

sample_data  tips.csv

In [2]:
import pandas as pd

df = pd.read_csv('tips.csv')

# option 2
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# Перші 5 рядків
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# Розмір датасету (shape)
display(df.shape)

(244, 7)

In [5]:
# Назви всіх колонок
display(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [6]:
# Інформація про типи даних (info)
display(df.info)

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [7]:
# Колонкa total_bill
total_bill = df['total_bill']
print(total_bill)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [8]:
# Колонки total_bill та tip
selected = df[['total_bill', 'tip']]
print(selected)

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [9]:
# Перші 10 рядків
display(df.head(10))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [10]:
# Рядок з індексом 5
print(df.iloc[5])

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [11]:
# Всі рахунки більше 20 доларів

high_bills = df[df['total_bill'] > 20]
print(len(high_bills))

display(high_bills.head(5))

97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [12]:
# Всі відвідувачі-жінки

females = df[df['sex'] == 'Female']
print(len(females))

display(females.head(5))

87

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [13]:
# Рахунки на вечерю

dinners = df[df['time'] == 'Dinner']
print(len(dinners))

display(dinners.head(5))

176

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
# Рахунки на вечерю з сумою чеку більше 30 доларів

expensive_dinners = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)]
print(len(expensive_dinners))

display(expensive_dinners.head(5))

27

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [15]:
# Середній розмір рахунку на всьому наборі даних
avg = df['total_bill'].mean()
print(f'Average bill - {avg}')
print()

# Максимальні чайові
max_tips = df['tip'].max()
print(f'Max tips - {max_tips}')
print()

# Скільки в наборі даних рахунків за обіди і за вечері
print(df['time'].value_counts())
print()

# Кількість пропущених значень у всіх колонках
df.isnull().sum()

Average bill - 19.78594262295082

Max tips - 10.0

time
Dinner    176
Lunch      68
Name: count, dtype: int64

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [16]:
# Середній рахунок за статтю
by_sex = df.groupby('sex')['total_bill'].mean()
print("Average bill by sex:")
by_sex

Average bill by sex:

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [17]:
# Середні чайові за днем тижня
by_day = df.groupby('day')['tip'].mean()
print("Average tips by day:")
by_day

Average tips by day:

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

In [18]:
# Скільки відвідувачів у кожен день
visitors = df.groupby('day')['size'].sum()
print("Total visitors by day:")
visitors

Total visitors by day:

day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [19]:
df['tip_percentage'] = df['tip'] / df['total_bill'] * 100

display(df.head(10))

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765
5       25.29  4.71    Male     No  Sun  Dinner     4       18.623962
6        8.77  2.00    Male     No  Sun  Dinner     2       22.805017
7       26.88  3.12    Male     No  Sun  Dinner     4       11.607143
8       15.04  1.96    Male     No  Sun  Dinner     2       13.031915
9       14.78  3.23    Male     No  Sun  Dinner     2       21.853857

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [20]:
# За розміром рахунку (зростання)
df_sorted_bill = df.sort_values('total_bill', ascending=True)
display(df_sorted_bill.head(5))

     total_bill   tip     sex smoker   day    time  size  tip_percentage
67         3.07  1.00  Female    Yes   Sat  Dinner     1       32.573290
92         5.75  1.00  Female    Yes   Fri  Dinner     2       17.391304
111        7.25  1.00  Female     No   Sat  Dinner     1       13.793103
172        7.25  5.15    Male    Yes   Sun  Dinner     2       71.034483
149        7.51  2.00    Male     No  Thur   Lunch     2       26.631158

In [21]:
# За чайовими (спадання)
df_sorted_tips = df.sort_values('tip', ascending=False)
display(df_sorted_tips.head(5))

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3       19.681165
212       48.33   9.00  Male     No   Sat  Dinner     4       18.621974
23        39.42   7.58  Male     No   Sat  Dinner     4       19.228818
59        48.27   6.73  Male     No   Sat  Dinner     4       13.942407
141       34.30   6.70  Male     No  Thur   Lunch     6       19.533528

In [22]:
# Top-5 tips
top_tips = df.nlargest(5, 'tip')
top_tips

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3       19.681165
212       48.33   9.00  Male     No   Sat  Dinner     4       18.621974
23        39.42   7.58  Male     No   Sat  Dinner     4       19.228818
59        48.27   6.73  Male     No   Sat  Dinner     4       13.942407
141       34.30   6.70  Male     No  Thur   Lunch     6       19.533528